(()=>{
	var form=document.forms["loginForm"],
		txtName=form.uname,
		txtPwd=form.upwd,
		valiTip=form.children[2],//错误信息提示
		btnLogin=form.elements["btnLogin"];
	btnLogin.onclick=function(){
		if(txtName.value.trim()===""){
			valiTip.style.display="block";
			valiTip.innerHTML="用户名不能为空";
		}else if(txtPwd.value.trim()===""){
			valiTip.style.display="block";
			valiTip.innerHTML="用户密码不能为空";
		}else{
			ajax({
				type:"post",
				url:"data/login.php",
				data:"&uname="+txtName.value+"&upwd="+txtPwd.value
			}).then(text=>{
				if(text=="true"){
					alert("登录成功!");
					location="index.html";
				}else{
					valiTip.style.display="block";
					valiTip.innerHTML="用户名或密码错误!";
				}
				})
		}
	}
})()